name: Test bun

on:
  pull_request:
    branches:
      - main
jobs:
  test-app:
    runs-on: ubuntu-latest
    steps:
      - name: Copies code
        uses: actions/checkout@v4

      - name: build and test bun
        run: docker compose up
